### ISSUE TITLE
`GlyphItemIter` intialization

### ISSUE THREAD

**Issue by velyan** [gtk-rs/pango#160]
Hey 👋 

I'm having some trouble using the `GlyphItemIter` interface.  I can't figure out how to instantiate it.  

The [Pango interface](https://github.com/GNOME/pango/blob/cdb88930da73bdbeb0e6167825121435d7e5e99f/pango/pango-glyph-item.h#L85) suggests passing an uninitialized variable to `pango_glyph_item_iter_init_start`, but I'm not sure how to achieve this in Rust. 

I tried making a fix by adding the following method to the  `GlyphItemIter` impl block:
```
    pub fn new_start() -> GlyphItemIter {
        unsafe { GlyphItemIter(Boxed::uninitialized()) }
    }
```
which compiles, but I get the following error when I try to use it:
```
(process:20824): GLib-GObject-CRITICAL **: 12:10:05.489: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed
```

Any ideas what I might be missing?

**Comment by EPashkin** [comment]
This method not helps?
https://gtk-rs.org/docs/pango/struct.GlyphItemIter.html#method.init_start

**Comment by velyan** [comment]
The issue is that it's not a method, but an associated function (takes `self` as a param).
And there is no method exposed for instantiating `self`.

**Comment by EPashkin** [comment]
Sorry, missed that part.
All boxed implement [trait `Uninitialized`](https://gtk-rs.org/docs/glib/translate/trait.Uninitialized.html)
```
    pub fn init_start2(glyph_item: &mut GlyphItem, text: &str) -> Option<GlyphItemIter> {
        unsafe {
let iter: GlyphItemIter = Uninitialized::uninitialized();
let res =            from_glib(pango_sys::pango_glyph_item_iter_init_start(
                iter.to_glib_none_mut().0,
                glyph_item.to_glib_none_mut().0,
                text.to_glib_none().0,
            ))
        }
if (!res) {
   None
} else {
Some(iter)
}
  
    }
```
Maybe with "mut_override" for `GlyphItem` to remove "&mut"

**Comment by velyan** [comment]
Thanks! This compiles:
```
    pub fn init_start2(glyph_item: &mut GlyphItem, text: &str) -> Option<GlyphItemIter> {
        unsafe {
            let mut iter: GlyphItemIter = GlyphItemIter(Uninitialized::uninitialized());
            let res: bool = from_glib(pango_sys::pango_glyph_item_iter_init_start(
                iter.to_glib_none_mut().0,
                glyph_item.to_glib_none_mut().0,
                text.to_glib_none().0,
            ));
            if !res {
                None
            } else {
                Some(iter)
            }
        }
    }
```

But I get the same panic at runtime :(

**Comment by EPashkin** [comment]
Can you check backtrace for panic source?
Also IMHO better not create `GlyphItemIter` directly but call its `uninitialized`

**Comment by velyan** [comment]
```
thread 'main' panicked at 'not yet implemented', /Users/velislavayanchina/Projects/pango/src/auto/glyph_item_iter.rs:9:1
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: <alloc::collections::CollectionAllocErr as core::convert::From<core::alloc::AllocErr>>::from
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:408
   6: <pango::auto::glyph_item_iter::MemoryManager as glib::boxed::BoxedMemoryManager<pango_sys::PangoGlyphItemIter>>::init
             at /Users/velislavayanchina/Projects/pango/<::glib::boxed::glib_boxed_wrapper macros>:184
   7: alloc::alloc::realloc
             at /Users/velislavayanchina/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.8.2/src/boxed.rs:370
   8: <pango::auto::item::MemoryManager as glib::boxed::BoxedMemoryManager<pango_sys::PangoItem>>::clear
             at /Users/velislavayanchina/Projects/pango/src/auto/glyph_item_iter.rs:23
   9: pango_test::main
             at src/main.rs:52
  10: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  12: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  13: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  14: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  15: pango_test::main
```

If I use this 
`let mut iter: GlyphItemIter = Uninitialized::uninitialized();` 
I get a compiler error 
`the trait `glib::translate::Uninitialized` is not implemented for `auto::glyph_item_iter::GlyphItemIter`

**Comment by EPashkin** [comment]
Seems we forgot to add `free` and `clear` for `GlyphItemIter`

**Comment by EPashkin** [comment]
I will try to fix it in git version.

**Comment by EPashkin** [comment]
While iterator can be created now I don't understand how it cab be used.
There no getters and `GlyphItem` also has none.
